file(GLOB_RECURSE GHOSTHUNT_INCLUDE_FILES ${GHOSTHUNT_SOURCE_DIR}/src/*.h)
file(GLOB_RECURSE GHOSTHUNT_MAIN_FILE ${GHOSTHUNT_SOURCE_DIR}/src/main.cpp)
file(GLOB_RECURSE GHOSTHUNT_SRC_FILES ${GHOSTHUNT_SOURCE_DIR}/src/GhostHunt/*.cpp)
